import type { AssetInput } from '@pascal-app/core/schema'

/**
 * Small built-in catalog for standalone/headless MCP use.
 *
 * The editor has a much larger UI catalog, but depending on `@pascal-app/editor`
 * from the MCP package would pull browser/React code into the headless server.
 * These entries mirror the stable IDs and asset paths used by the editor for
 * common AI-generated residential layouts.
 *
 * `dimensions` are the measured model bounds, `role` and `clearance` the
 * interior-design facts `review_layout` reads: role says what the item is for
 * (seat/table/bed/storage/fixture/appliance/media/decor), clearance the free
 * space it needs — front (in front of its face), back (pull-out space behind
 * it), sides (each lateral side). Item fronts face local +Z; orient_item turns
 * them to face a point or another node.
 */
export const MCP_CATALOG_ITEMS: AssetInput[] = [
  {
    id: 'double-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Double Bed',
    thumbnail: '/items/double-bed/thumbnail.webp',
    src: '/items/double-bed/model.glb',
    dimensions: [1.52, 0.71, 2],
    offset: [0, 0, -0.03],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'bed',
    clearance: { front: 0.6, sides: 0.6 },
  },
  {
    id: 'single-bed',
    category: 'furniture',
    tags: ['floor', 'bedroom'],
    name: 'Single Bed',
    thumbnail: '/items/single-bed/thumbnail.webp',
    src: '/items/single-bed/model.glb',
    dimensions: [1.08, 0.6, 2.14],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'bed',
    clearance: { front: 0.6, sides: 0.6 },
  },
  {
    id: 'bedside-table',
    category: 'furniture',
    tags: ['floor', 'bedroom', 'storage'],
    name: 'Bedside Table',
    thumbnail: '/items/bedside-table/thumbnail.webp',
    src: '/items/bedside-table/model.glb',
    dimensions: [0.45, 0.48, 0.46],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.48 },
    role: 'storage',
    clearance: { front: 0.4 },
  },
  {
    id: 'dresser',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Dresser',
    thumbnail: '/items/dresser/thumbnail.webp',
    src: '/items/dresser/model.glb',
    dimensions: [1.23, 0.73, 0.61],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.73 },
    role: 'storage',
    clearance: { front: 0.9 },
  },
  {
    id: 'closet',
    category: 'furniture',
    tags: ['floor', 'storage', 'bedroom'],
    name: 'Closet',
    thumbnail: '/items/closet/thumbnail.webp',
    src: '/items/closet/model.glb',
    dimensions: [1.95, 2.26, 0.6],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
    clearance: { front: 0.9 },
  },
  {
    id: 'sofa',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Sofa',
    thumbnail: '/items/sofa/thumbnail.webp',
    src: '/items/sofa/model.glb',
    dimensions: [2.06, 0.74, 1.01],
    offset: [0, 0.01, 0.05],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { front: 0.5 },
  },
  {
    id: 'livingroom-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Livingroom Chair',
    thumbnail: '/items/livingroom-chair/thumbnail.webp',
    src: '/items/livingroom-chair/model.glb',
    dimensions: [1.1, 0.75, 1.07],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { front: 0.4 },
  },
  {
    id: 'lounge-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Lounge Chair',
    thumbnail: '/items/lounge-chair/thumbnail.webp',
    src: '/items/lounge-chair/model.glb',
    dimensions: [0.68, 1.03, 1.26],
    offset: [0, 0, 0.09],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { front: 0.4 },
  },
  {
    id: 'bean-bag',
    category: 'furniture',
    tags: ['floor', 'seating', 'living'],
    name: 'Bean Bag',
    thumbnail: '/items/bean-bag/thumbnail.webp',
    src: '/items/bean-bag/model.glb',
    dimensions: [1.05, 1.07, 1.13],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { front: 0.4 },
  },
  {
    id: 'stool',
    category: 'furniture',
    tags: ['floor', 'seating'],
    name: 'Stool',
    thumbnail: '/items/stool/thumbnail.webp',
    src: '/items/stool/model.glb',
    dimensions: [0.52, 1.16, 0.55],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { front: 0.3 },
  },
  {
    id: 'coffee-table',
    category: 'furniture',
    tags: ['floor', 'table', 'living'],
    name: 'Coffee Table',
    thumbnail: '/items/coffee-table/thumbnail.webp',
    src: '/items/coffee-table/model.glb',
    dimensions: [1.72, 0.3, 1.04],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.3 },
    role: 'table',
    clearance: { sides: 0.4 },
  },
  {
    id: 'tv-stand',
    category: 'furniture',
    tags: ['floor', 'storage', 'living'],
    name: 'TV Stand',
    thumbnail: '/items/tv-stand/thumbnail.webp',
    src: '/items/tv-stand/model.glb',
    dimensions: [1.86, 0.35, 0.32],
    offset: [0, 0.21, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.35 },
    role: 'storage',
    clearance: { front: 0.6 },
  },
  {
    id: 'television',
    category: 'furniture',
    tags: ['floor', 'electronics', 'living', 'media'],
    name: 'Television',
    thumbnail: '/items/television/thumbnail.webp',
    src: '/items/television/model.glb',
    dimensions: [1.62, 1.07, 0.38],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'media',
    clearance: { front: 0.8 },
  },
  {
    id: 'shelf',
    category: 'furniture',
    tags: ['wall', 'storage'],
    name: 'Shelf',
    thumbnail: '/items/shelf/thumbnail.webp',
    src: '/items/shelf/model.glb',
    dimensions: [0.74, 0.04, 0.32],
    offset: [0, 0.1, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    surface: { height: 0.12 },
    role: 'storage',
  },
  {
    id: 'bookshelf',
    category: 'furniture',
    tags: ['floor', 'storage', 'office', 'living'],
    name: 'Bookshelf',
    thumbnail: '/items/bookshelf/thumbnail.webp',
    src: '/items/bookshelf/model.glb',
    dimensions: [0.93, 1.99, 0.33],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
    clearance: { front: 0.7 },
  },
  {
    id: 'dining-table',
    category: 'furniture',
    tags: ['floor', 'table', 'dining'],
    name: 'Dining Table',
    thumbnail: '/items/dining-table/thumbnail.webp',
    src: '/items/dining-table/model.glb',
    dimensions: [2.16, 0.7, 0.95],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.7 },
    role: 'table',
  },
  {
    id: 'dining-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'dining'],
    name: 'Dining Chair',
    thumbnail: '/items/dining-chair/thumbnail.webp',
    src: '/items/dining-chair/model.glb',
    dimensions: [0.47, 0.87, 0.5],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { back: 0.6, front: 0.35 },
  },
  {
    id: 'desk',
    category: 'furniture',
    tags: ['floor', 'office', 'workspace'],
    name: 'Desk',
    thumbnail: '/items/desk/thumbnail.webp',
    src: '/items/desk/model.glb',
    dimensions: [1.83, 0.93, 0.85],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.75 },
    role: 'desk',
    clearance: { front: 0.9 },
  },
  {
    id: 'office-chair',
    category: 'furniture',
    tags: ['floor', 'seating', 'office'],
    name: 'Office Chair',
    thumbnail: '/items/office-chair/thumbnail.webp',
    src: '/items/office-chair/model.glb',
    dimensions: [0.66, 1.16, 0.69],
    offset: [0, 0, 0.03],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'seat',
    clearance: { back: 0.7, front: 0.3 },
  },
  {
    id: 'kitchen',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen'],
    name: 'Kitchen',
    thumbnail: '/items/kitchen/thumbnail.webp',
    src: '/items/kitchen/model.glb',
    dimensions: [2.38, 1.03, 0.84],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 1.0 },
  },
  {
    id: 'kitchen-counter',
    category: 'kitchen',
    tags: ['floor', 'large', 'storage', 'kitchen'],
    name: 'Kitchen Counter',
    thumbnail: '/items/kitchen-counter/thumbnail.webp',
    src: '/items/kitchen-counter/model.glb',
    dimensions: [1.96, 0.73, 0.63],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.73 },
    role: 'fixture',
    clearance: { front: 1.0 },
  },
  {
    id: 'stove',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen'],
    name: 'Stove',
    thumbnail: '/items/stove/thumbnail.webp',
    src: '/items/stove/model.glb',
    dimensions: [0.92, 0.85, 0.76],
    offset: [0, 0, -0.05],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
    clearance: { front: 1.0 },
  },
  {
    id: 'fridge',
    category: 'kitchen',
    tags: ['floor', 'large', 'kitchen'],
    name: 'Fridge',
    thumbnail: '/items/fridge/thumbnail.webp',
    src: '/items/fridge/model.glb',
    dimensions: [0.7, 1.92, 0.72],
    offset: [0, 0, -0.05],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
    clearance: { front: 0.9 },
  },
  {
    id: 'microwave',
    category: 'kitchen',
    tags: ['countertop', 'kitchen'],
    name: 'Microwave',
    thumbnail: '/items/microwave/thumbnail.webp',
    src: '/items/microwave/model.glb',
    dimensions: [0.52, 0.27, 0.41],
    offset: [0, 0, -0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
    clearance: { front: 0.6 },
  },
  {
    id: 'toilet',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Toilet',
    thumbnail: '/items/toilet/thumbnail.webp',
    src: '/items/toilet/model.glb',
    dimensions: [0.42, 0.82, 0.72],
    offset: [0, 0, -0.23],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 0.6, sides: 0.2 },
  },
  {
    id: 'bathroom-sink',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Bathroom Sink',
    thumbnail: '/items/bathroom-sink/thumbnail.webp',
    src: '/items/bathroom-sink/model.glb',
    dimensions: [1.83, 0.97, 0.63],
    offset: [0.1, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 0.75 },
  },
  {
    id: 'shower-square',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Squared Shower',
    thumbnail: '/items/shower-square/thumbnail.webp',
    src: '/items/shower-square/model.glb',
    dimensions: [0.81, 1.8, 0.81],
    offset: [0.4, 0, -0.4],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 0.6 },
  },
  {
    id: 'bathtub',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Bathtub',
    thumbnail: '/items/bathtub/thumbnail.webp',
    src: '/items/bathtub/model.glb',
    dimensions: [2.34, 0.79, 1.11],
    offset: [0, 0, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { sides: 0.7 },
  },
  {
    id: 'washing-machine',
    category: 'bathroom',
    tags: ['floor', 'large', 'electronics', 'laundry'],
    name: 'Washing Machine',
    thumbnail: '/items/washing-machine/thumbnail.webp',
    src: '/items/washing-machine/model.glb',
    dimensions: [0.6, 0.86, 0.53],
    offset: [0, 0, -0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
    clearance: { front: 0.9 },
  },
  {
    id: 'drying-rack',
    category: 'bathroom',
    tags: ['floor', 'laundry'],
    name: 'Drying Rack',
    thumbnail: '/items/drying-rack/thumbnail.webp',
    src: '/items/drying-rack/model.glb',
    dimensions: [1.79, 1.05, 0.58],
    offset: [0, -0.01, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    clearance: { front: 0.6 },
  },
  {
    id: 'coat-rack',
    category: 'furniture',
    tags: ['floor', 'storage', 'entry'],
    name: 'Coat Rack',
    thumbnail: '/items/coat-rack/thumbnail.webp',
    src: '/items/coat-rack/model.glb',
    dimensions: [0.33, 1.76, 0.33],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
    clearance: { front: 0.4 },
  },
  {
    id: 'rectangular-carpet',
    category: 'furniture',
    tags: ['floor', 'rug', 'living', 'decor'],
    name: 'Rectangular Carpet',
    thumbnail: '/items/rectangular-carpet/thumbnail.webp',
    src: '/items/rectangular-carpet/model.glb',
    dimensions: [2.78, 0.04, 1.81],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
    role: 'decor',
  },
  {
    id: 'floor-lamp',
    category: 'furniture',
    tags: ['floor', 'lighting', 'living', 'decor'],
    name: 'Floor Lamp',
    thumbnail: '/items/floor-lamp/thumbnail.webp',
    src: '/items/floor-lamp/model.glb',
    dimensions: [0.7, 1.86, 0.69],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'table-lamp',
    category: 'furniture',
    tags: ['countertop', 'lighting', 'decor'],
    name: 'Table Lamp',
    thumbnail: '/items/table-lamp/thumbnail.webp',
    src: '/items/table-lamp/model.glb',
    dimensions: [0.29, 0.74, 0.67],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'indoor-plant',
    category: 'furniture',
    tags: ['floor', 'decor', 'living'],
    name: 'Indoor Plant',
    thumbnail: '/items/indoor-plant/thumbnail.webp',
    src: '/items/indoor-plant/model.glb',
    dimensions: [0.69, 1.63, 0.83],
    offset: [-0.05, 0, 0.07],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'easel',
    category: 'furniture',
    tags: ['floor', 'decor', 'studio'],
    name: 'Easel',
    thumbnail: '/items/easel/thumbnail.webp',
    src: '/items/easel/model.glb',
    dimensions: [0.99, 2.32, 0.55],
    offset: [0, 0.04, 0.01],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.7 },
  },
  {
    id: 'piano',
    category: 'furniture',
    tags: ['floor', 'decor', 'living'],
    name: 'Piano',
    thumbnail: '/items/piano/thumbnail.webp',
    src: '/items/piano/model.glb',
    dimensions: [1.54, 1.44, 0.69],
    offset: [0, 0, 0.02],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.9 },
  },
  {
    id: 'picture',
    category: 'furniture',
    tags: ['wall', 'decor', 'art', 'frame'],
    name: 'Picture',
    thumbnail: '/items/picture/thumbnail.webp',
    src: '/items/picture/model.glb',
    dimensions: [1.47, 0.82, 0.06],
    offset: [0, 0.41, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'decor',
  },
  {
    id: 'wall-art-06',
    category: 'furniture',
    tags: ['wall', 'decor', 'art', 'frame'],
    name: 'Wall Art',
    thumbnail: '/items/wall-art-06/thumbnail.webp',
    src: '/items/wall-art-06/model.glb',
    dimensions: [0.54, 0.89, 0.03],
    offset: [0, 0.448, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'decor',
  },
  {
    id: 'round-mirror',
    category: 'furniture',
    tags: ['wall', 'decor', 'mirror', 'bathroom', 'entry'],
    name: 'Round Mirror',
    thumbnail: '/items/round-mirror/thumbnail.webp',
    src: '/items/round-mirror/model.glb',
    dimensions: [0.57, 0.57, 0.05],
    offset: [0, 0.2848, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'decor',
  },
  {
    id: 'rectangular-mirror',
    category: 'furniture',
    tags: ['floor', 'decor', 'mirror', 'bedroom', 'entry'],
    name: 'Standing Mirror',
    thumbnail: '/items/rectangular-mirror/thumbnail.webp',
    src: '/items/rectangular-mirror/model.glb',
    dimensions: [0.88, 1.57, 0.25],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'ceiling-lamp',
    category: 'furniture',
    tags: ['ceiling', 'lighting', 'pendant', 'decor'],
    name: 'Ceiling Lamp',
    thumbnail: '/items/ceiling-lamp/thumbnail.webp',
    src: '/items/ceiling-lamp/model.glb',
    dimensions: [0.55, 0.86, 0.55],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    role: 'decor',
  },
  {
    id: 'ceiling-fan',
    category: 'furniture',
    tags: ['ceiling', 'lighting', 'fan', 'decor'],
    name: 'Ceiling Fan',
    thumbnail: '/items/ceiling-fan/thumbnail.webp',
    src: '/items/ceiling-fan/model.glb',
    dimensions: [0.92, 0.35, 1.03],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    role: 'decor',
  },
  {
    id: 'recessed-light',
    category: 'furniture',
    tags: ['ceiling', 'lighting', 'spotlight'],
    name: 'Recessed Light',
    thumbnail: '/items/recessed-light/thumbnail.webp',
    src: '/items/recessed-light/model.glb',
    dimensions: [0.22, 0.06, 0.22],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    recessed: true,
    role: 'decor',
  },
  {
    id: 'round-carpet',
    category: 'furniture',
    tags: ['floor', 'rug', 'decor'],
    name: 'Round Carpet',
    thumbnail: '/items/round-carpet/thumbnail.webp',
    src: '/items/round-carpet/model.glb',
    dimensions: [1.99, 0.04, 1.99],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.03 },
    role: 'decor',
  },
  {
    id: 'books',
    category: 'furniture',
    tags: ['countertop', 'decor', 'study', 'shelf'],
    name: 'Books',
    thumbnail: '/items/books/thumbnail.webp',
    src: '/items/books/model.glb',
    dimensions: [0.22, 0.22, 0.18],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'small-indoor-plant',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation'],
    name: 'Small Plant',
    thumbnail: '/items/small-indoor-plant/thumbnail.webp',
    src: '/items/small-indoor-plant/model.glb',
    dimensions: [0.39, 0.67, 0.38],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'kitchen-shelf',
    category: 'kitchen',
    tags: ['wall', 'storage', 'kitchen'],
    name: 'Kitchen Shelf',
    thumbnail: '/items/kitchen-shelf/thumbnail.webp',
    src: '/items/kitchen-shelf/model.glb',
    dimensions: [2.2, 0.89, 0.52],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    surface: { height: 0.75 },
    role: 'storage',
  },
  {
    id: 'shower-rug',
    category: 'bathroom',
    tags: ['floor', 'rug', 'bathroom', 'decor'],
    name: 'Bath Mat',
    thumbnail: '/items/shower-rug/thumbnail.webp',
    src: '/items/shower-rug/model.glb',
    dimensions: [0.77, 0.03, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 0.02 },
    role: 'decor',
  },
  {
    id: 'toilet-paper',
    category: 'bathroom',
    tags: ['wall', 'bathroom', 'decor'],
    name: 'Toilet Paper Holder',
    thumbnail: '/items/toilet-paper/thumbnail.webp',
    src: '/items/toilet-paper/model.glb',
    dimensions: [0.25, 0.26, 0.24],
    offset: [0, 0.13, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'fixture',
  },
  {
    id: 'fruits',
    category: 'kitchen',
    tags: ['countertop', 'decor', 'kitchen', 'dining'],
    name: 'Fruit Bowl',
    thumbnail: '/items/fruits/thumbnail.webp',
    src: '/items/fruits/model.glb',
    dimensions: [0.39, 0.27, 0.39],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'kettle',
    category: 'appliance',
    tags: ['countertop', 'appliance', 'kitchen'],
    name: 'Kettle',
    thumbnail: '/items/kettle/thumbnail.webp',
    src: '/items/kettle/model.glb',
    dimensions: [0.23, 0.25, 0.18],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen',
    tags: ['countertop', 'kitchen', 'decor'],
    name: 'Kitchen Utensils',
    thumbnail: '/items/kitchen-utensils/thumbnail.webp',
    src: '/items/kitchen-utensils/model.glb',
    dimensions: [0.22, 0.49, 0.21],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'cutting-board',
    category: 'kitchen',
    tags: ['countertop', 'kitchen', 'decor'],
    name: 'Cutting Board',
    thumbnail: '/items/cutting-board/thumbnail.webp',
    src: '/items/cutting-board/model.glb',
    dimensions: [0.26, 0.07, 0.41],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'wine-bottle',
    category: 'kitchen',
    tags: ['countertop', 'decor', 'dining'],
    name: 'Wine Bottle',
    thumbnail: '/items/wine-bottle/thumbnail.webp',
    src: '/items/wine-bottle/model.glb',
    dimensions: [0.38, 0.35, 0.16],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'laundry-bag',
    category: 'bathroom',
    tags: ['floor', 'laundry', 'bathroom', 'storage'],
    name: 'Laundry Bag',
    thumbnail: '/items/laundry-bag/thumbnail.webp',
    src: '/items/laundry-bag/model.glb',
    dimensions: [0.46, 0.77, 0.47],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
  },
  {
    id: 'trash-bin',
    category: 'bathroom',
    tags: ['floor', 'bathroom', 'office', 'storage'],
    name: 'Trash Bin',
    thumbnail: '/items/trash-bin/thumbnail.webp',
    src: '/items/trash-bin/model.glb',
    dimensions: [0.35, 0.59, 0.41],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
  },
  {
    id: 'cactus',
    category: 'furniture',
    tags: ['countertop', 'decor', 'vegetation'],
    name: 'Cactus',
    thumbnail: '/items/cactus/thumbnail.webp',
    src: '/items/cactus/model.glb',
    dimensions: [0.33, 0.39, 0.27],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'guitar',
    category: 'furniture',
    tags: ['floor', 'decor', 'music', 'living'],
    name: 'Guitar',
    thumbnail: '/items/guitar/thumbnail.webp',
    src: '/items/guitar/model.glb',
    dimensions: [0.39, 1.17, 0.08],
    offset: [0, 0.32, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'bunkbed',
    category: 'furniture',
    tags: ['floor', 'bedroom', 'kids', 'bed'],
    name: 'Bunk Bed',
    thumbnail: '/items/bunkbed/thumbnail.webp',
    src: '/items/bunkbed/model.glb',
    dimensions: [1.65, 1.54, 0.98],
    offset: [0, 0, -0.09],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'bed',
    clearance: { front: 0.8 },
  },
  {
    id: 'computer',
    category: 'furniture',
    tags: ['electronics', 'desk', 'office', 'screen'],
    name: 'Computer',
    thumbnail: '/items/computer/thumbnail.webp',
    src: '/items/computer/model.glb',
    dimensions: [0.67, 0.47, 0.19],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'media',
  },
  {
    id: 'pool-table',
    category: 'furniture',
    tags: ['floor', 'game', 'hobby', 'living'],
    name: 'Pool Table',
    thumbnail: '/items/pool-table/thumbnail.webp',
    src: '/items/pool-table/model.glb',
    dimensions: [2.1, 0.98, 3.49],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'table',
    clearance: { front: 1.2, back: 1.2, sides: 1.2 },
  },
  {
    id: 'stereo-speaker',
    category: 'furniture',
    tags: ['floor', 'media', 'music', 'living'],
    name: 'Stereo Speaker',
    thumbnail: '/items/stereo-speaker/thumbnail.webp',
    src: '/items/stereo-speaker/model.glb',
    dimensions: [0.22, 1.0, 0.34],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'media',
  },
  {
    id: 'coffee-machine',
    category: 'kitchen',
    tags: ['appliance', 'counter', 'kitchen'],
    name: 'Coffee Machine',
    thumbnail: '/items/coffee-machine/thumbnail.webp',
    src: '/items/coffee-machine/model.glb',
    dimensions: [0.15, 0.23, 0.23],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
  },
  {
    id: 'toaster',
    category: 'kitchen',
    tags: ['appliance', 'counter', 'kitchen'],
    name: 'Toaster',
    thumbnail: '/items/toaster/thumbnail.webp',
    src: '/items/toaster/model.glb',
    dimensions: [0.27, 0.23, 0.17],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
  },
  {
    id: 'freezer',
    category: 'kitchen',
    tags: ['floor', 'appliance', 'kitchen', 'laundry'],
    name: 'Freezer',
    thumbnail: '/items/freezer/thumbnail.webp',
    src: '/items/freezer/model.glb',
    dimensions: [0.43, 0.92, 0.29],
    offset: [0.21, 0, -0.14],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
    clearance: { front: 0.7 },
  },
  {
    id: 'hood',
    category: 'kitchen',
    tags: ['wall', 'appliance', 'kitchen', 'extractor'],
    name: 'Range Hood',
    thumbnail: '/items/hood/thumbnail.webp',
    src: '/items/hood/model.glb',
    dimensions: [1.2, 0.52, 0.51],
    offset: [0, 0.27, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'appliance',
  },
  {
    id: 'kitchen-cabinet',
    category: 'kitchen',
    tags: ['floor', 'storage', 'kitchen', 'counter'],
    name: 'Kitchen Cabinet',
    thumbnail: '/items/kitchen-cabinet/thumbnail.webp',
    src: '/items/kitchen-cabinet/model.glb',
    dimensions: [1.64, 1.09, 0.76],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    surface: { height: 1.0 },
    role: 'storage',
    clearance: { front: 0.9 },
  },
  {
    id: 'tub',
    category: 'bathroom',
    tags: ['floor', 'fixture', 'bathroom', 'bath'],
    name: 'Freestanding Tub',
    thumbnail: '/items/tub/thumbnail.webp',
    src: '/items/tub/model.glb',
    dimensions: [2.34, 0.78, 1.11],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 0.6 },
  },
  {
    id: 'thermostat',
    category: 'furniture',
    tags: ['wall', 'fixture', 'climate'],
    name: 'Thermostat',
    thumbnail: '/items/thermostat/thumbnail.webp',
    src: '/items/thermostat/model.glb',
    dimensions: [0.05, 0.05, 0.05],
    offset: [0, 0.03, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'wall-side',
    role: 'fixture',
  },
  {
    id: 'smoke-detector',
    category: 'furniture',
    tags: ['ceiling', 'fixture', 'safety'],
    name: 'Smoke Detector',
    thumbnail: '/items/smoke-detector/thumbnail.webp',
    src: '/items/smoke-detector/model.glb',
    dimensions: [0.16, 0.05, 0.16],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    role: 'fixture',
  },
  {
    id: 'exercise-bike',
    category: 'furniture',
    tags: ['floor', 'gym', 'sport'],
    name: 'Exercise Bike',
    thumbnail: '/items/exercise-bike/thumbnail.webp',
    src: '/items/exercise-bike/model.glb',
    dimensions: [0.94, 1.41, 0.59],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.5 },
  },
  {
    id: 'barbell',
    category: 'furniture',
    tags: ['floor', 'gym', 'sport'],
    name: 'Barbell',
    thumbnail: '/items/barbell/thumbnail.webp',
    src: '/items/barbell/model.glb',
    dimensions: [0.38, 0.38, 1.72],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'barbell-stand',
    category: 'furniture',
    tags: ['floor', 'gym', 'sport', 'storage'],
    name: 'Barbell Stand',
    thumbnail: '/items/barbell-stand/thumbnail.webp',
    src: '/items/barbell-stand/model.glb',
    dimensions: [1.33, 1.22, 1.72],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'storage',
  },
  {
    id: 'ironing-board',
    category: 'furniture',
    tags: ['floor', 'laundry', 'utility'],
    name: 'Ironing Board',
    thumbnail: '/items/ironing-board/thumbnail.webp',
    src: '/items/ironing-board/model.glb',
    dimensions: [1.31, 0.95, 0.48],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.6 },
  },
  {
    id: 'iron',
    category: 'furniture',
    tags: ['appliance', 'laundry', 'surface'],
    name: 'Iron',
    thumbnail: '/items/iron/thumbnail.webp',
    src: '/items/iron/model.glb',
    dimensions: [0.35, 0.23, 0.21],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'appliance',
  },
  {
    id: 'circular-ceiling-light',
    category: 'furniture',
    tags: ['ceiling', 'lighting', 'decor'],
    name: 'Circular Ceiling Light',
    thumbnail: '/items/circular-ceiling-light/thumbnail.webp',
    src: '/items/circular-ceiling-light/model.glb',
    dimensions: [0.21, 0.09, 0.21],
    offset: [0, 0.05, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'ceiling',
    role: 'decor',
  },
  {
    id: 'suspended-fireplace',
    category: 'furniture',
    tags: ['floor', 'fireplace', 'living', 'decor'],
    name: 'Suspended Fireplace',
    thumbnail: '/items/suspended-fireplace/thumbnail.webp',
    src: '/items/suspended-fireplace/model.glb',
    dimensions: [1.74, 4.22, 0.79],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.8 },
  },

  {
    id: 'threadmill',
    category: 'furniture',
    tags: ['floor', 'gym', 'sport'],
    name: 'Treadmill',
    thumbnail: '/items/threadmill/thumbnail.webp',
    src: '/items/threadmill/model.glb',
    dimensions: [2.1, 1.45, 0.9],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { back: 1.0 },
  },
  {
    id: 'toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'play'],
    name: 'Toy',
    thumbnail: '/items/toy/thumbnail.webp',
    src: '/items/toy/model.glb',
    dimensions: [0.29, 0.49, 0.33],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'car-toy',
    category: 'furniture',
    tags: ['floor', 'kids', 'play'],
    name: 'Car Toy',
    thumbnail: '/items/car-toy/thumbnail.webp',
    src: '/items/car-toy/model.glb',
    dimensions: [0.3, 0.38, 0.59],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'toilet-brush',
    category: 'bathroom',
    tags: ['floor', 'small', 'bathroom'],
    name: 'Toilet Brush',
    thumbnail: '/items/toilet-brush/thumbnail.webp',
    src: '/items/toilet-brush/model.glb',
    dimensions: [0.12, 0.56, 0.12],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'shower-angle',
    category: 'bathroom',
    tags: ['floor', 'large', 'bathroom'],
    name: 'Corner Shower',
    thumbnail: '/items/shower-angle/thumbnail.webp',
    src: '/items/shower-angle/model.glb',
    dimensions: [0.82, 1.8, 0.82],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'fixture',
    clearance: { front: 0.6 },
  },
  {
    id: 'scooter',
    category: 'furniture',
    tags: ['floor', 'kids', 'play'],
    name: 'Scooter',
    thumbnail: '/items/scooter/thumbnail.webp',
    src: '/items/scooter/model.glb',
    dimensions: [0.44, 0.84, 0.85],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'basket-hoop',
    category: 'furniture',
    tags: ['floor', 'kids', 'sport', 'play'],
    name: 'Basket Hoop',
    thumbnail: '/items/basket-hoop/thumbnail.webp',
    src: '/items/basket-hoop/model.glb',
    dimensions: [0.67, 1.77, 0.56],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
    clearance: { front: 0.5 },
  },
  {
    id: 'laundry-bag',
    category: 'furniture',
    tags: ['floor', 'small', 'storage', 'laundry'],
    name: 'Laundry Bag',
    thumbnail: '/items/laundry-bag/thumbnail.webp',
    src: '/items/laundry-bag/model.glb',
    dimensions: [0.47, 0.77, 0.46],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
  {
    id: 'sewing-machine',
    category: 'furniture',
    tags: ['surface', 'hobby', 'craft'],
    name: 'Sewing Machine',
    thumbnail: '/items/sewing-machine/thumbnail.webp',
    src: '/items/sewing-machine/model.glb',
    dimensions: [0.82, 0.68, 0.31],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    attachTo: 'surface',
    role: 'decor',
  },
  {
    id: 'skate',
    category: 'furniture',
    tags: ['floor', 'kids', 'play'],
    name: 'Skateboard',
    thumbnail: '/items/skate/thumbnail.webp',
    src: '/items/skate/model.glb',
    dimensions: [0.85, 0.11, 0.19],
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    role: 'decor',
  },
]

export function findCatalogItem(id: string): AssetInput | undefined {
  return MCP_CATALOG_ITEMS.find((item) => item.id === id)
}

/**
 * A catalog entry as an item's stored `asset`: defaults filled, optional
 * fields (surface, attachTo, front, clearance, role …) carried through.
 */
export function toItemAsset(asset: AssetInput) {
  return {
    id: asset.id,
    name: asset.name,
    category: asset.category,
    thumbnail: asset.thumbnail ?? '',
    src: asset.src,
    dimensions: asset.dimensions ?? [1, 1, 1],
    offset: asset.offset ?? [0, 0, 0],
    rotation: asset.rotation ?? [0, 0, 0],
    scale: asset.scale ?? [1, 1, 1],
    front: asset.front ?? 'z+',
    ...(asset.attachTo ? { attachTo: asset.attachTo } : {}),
    ...(asset.tags ? { tags: asset.tags } : {}),
    ...(asset.surface ? { surface: asset.surface } : {}),
    ...(asset.interactive ? { interactive: asset.interactive } : {}),
    ...(asset.clearance ? { clearance: asset.clearance } : {}),
    ...(asset.role ? { role: asset.role } : {}),
  }
}

/**
 * Rugs, mats and other floor-resting pieces low enough to host furniture on top —
 * they never block placements themselves and may sit under furniture footprints
 * (same ≤0.1 m surface rule the scene graph uses for low-profile item surfaces).
 */
export function isLowProfileAsset(asset: AssetInput): boolean {
  if (asset.attachTo) return false
  const height = asset.surface?.height ?? asset.dimensions?.[1] ?? 1
  return height <= 0.1
}

export function searchCatalogItems(args: {
  query: string
  category?: string | undefined
}): AssetInput[] {
  const terms = args.query.trim().toLowerCase().split(/\s+/).filter(Boolean)

  return MCP_CATALOG_ITEMS.filter((item) => {
    if (args.category && item.category !== args.category) return false
    const haystack = [item.id, item.name, item.category, ...(item.tags ?? [])]
      .join(' ')
      .toLowerCase()
    return terms.every((term) => haystack.includes(term))
  })
}
